### ISSUE TITLE
Problem: there is no way to access the blog article(s)

### ISSUE THREAD

**Issue by robinbb** [Granola-Team/site#52]

**Comment by jstavh** [comment]
Solved here: https://github.com/Granola-Team/site/pull/61

**Comment by robinbb** [comment]
@jstavh Apologies for lack of detail from me. I had intended:
1. To create a nav button for the blog
2. To remove the "Mina FAQ" button from the home page
3. To transform the Mina FAQ into a regular blog article
4. To create an index for all blog articels (of which there would then be exactly 2)
5. ... which would allow me to write further blog articles in the 'blog' directory, in Markdown.

**Comment by jstavh** [comment]
> @jstavh Apologies for lack of detail from me. I had intended:
> 
> 1. To create a nav button for the blog
> 2. To remove the "Mina FAQ" button from the home page
> 3. To transform the Mina FAQ into a regular blog article
> 4. To create an index for all blog articels (of which there would then be exactly 2)
> 5. ... which would allow me to write further blog articles in the 'blog' directory, in Markdown.

This recent commit addresses your points above: https://github.com/Granola-Team/site/pull/61/commits/06a78cbf33cdca56c520673b37a88848cf924e79 and two minor following commits.
