### ISSUE TITLE
Problem: there is no need for React yet React is imported in packages.json

### ISSUE THREAD

**Issue by robinbb** [Granola-Team/site#53]

**Comment by jstavh** [comment]
@robinbb I started this here https://github.com/Granola-Team/site/pull/60 and for our JSX files to render we need to use @astrojs/react, @astrojs/preact, or @astrojs/solid-js according to https://docs.astro.build/en/reference/errors/no-matching-renderer/ so please let me know which one you want.

**Comment by jstavh** [comment]
@robinbb -- I removed JSX/React in the above PR.
